services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    container_name: Nextjs_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/my-app:/app
      - /app/node_modules
    build:
      context: "./frontend/my-app"
      dockerfile: Dockerfile
    command: npm run dev
  django:
    container_name: django-backend
    build:
      context: "./Ecommerce_app"
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Ecommerce_app:/backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ENV=${DJANGO_ENV}
      - PYTHONUNBUFFERED=1
      - DJANGO_WATCH=1
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_SECRET=${PAYPAL_SECRET}
      - PAYPAL_API_BASE=${PAYPAL_API_BASE}
      - GRAPH_TENANT_ID=${GRAPH_TENANT_ID}
      - GRAPH_CLIENT_ID=${GRAPH_CLIENT_ID}
      - GRAPH_CLIENT_SECRET=${GRAPH_CLIENT_SECRET}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - SENDCLOUD_SECRET_KEY=${SENDCLOUD_SECRET_KEY}
      - SENDCLOUD_PUBLIC_KEY=${SENDCLOUD_PUBLIC_KEY}
      - SENDCLOUD_SENDER_ADDRESS_ID=${SENDCLOUD_SENDER_ADDRESS_ID}
      - SENDCLOUD_FROM_POSTCODE=${SENDCLOUD_FROM_POSTCODE}
    depends_on:
      - db
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  celery:
    build:
      context: "./Ecommerce_app"
      dockerfile: Dockerfile
    command: celery -A Ecommerce_app worker -l info
    volumes:
      - ./Ecommerce_app:/backend
    environment:
      - DJANGO_ENV=development
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - GRAPH_TENANT_ID=${GRAPH_TENANT_ID}
      - GRAPH_CLIENT_ID=${GRAPH_CLIENT_ID}
      - GRAPH_CLIENT_SECRET=${GRAPH_CLIENT_SECRET}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - django
      - redis
      - db
  stripe:
    image: stripe/stripe-cli
    container_name: stripe
    command:
      ["listen", "--forward-to", "http://django:8000/api/payments/webhook/"]
    volumes:
      - stripe-cli-config-2:/root/.config/stripe
    depends_on:
      - django
volumes:
  postgres_data:
  stripe-cli-config-2:
