services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net
  django-backend-prod:
    container_name: django-backend-prod
    build:
      context: ./Ecommerce_app
      dockerfile: Dockerfile.prod
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn Ecommerce_app.wsgi:application --bind 0.0.0.0:8000 --workers=4
      "
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ENV: ${DJANGO_ENV}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      POSTGRES_HOST: ${POSTGRES_HOST}
      TURNSTILE_SECRET_KEY: ${TURNSTILE_SECRET_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PAYPAL_SECRET: ${PAYPAL_SECRET}
      PAYPAL_API_BASE: ${PAYPAL_API_BASE}
      GRAPH_TENANT_ID: ${GRAPH_TENANT_ID}
      GRAPH_CLIENT_ID: ${GRAPH_CLIENT_ID}
      GRAPH_CLIENT_SECRET: ${GRAPH_CLIENT_SECRET}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    volumes:
      - ./Ecommerce_app/static:/code/static
      - ./Ecommerce_app/media:/code/media
      - ./Ecommerce_app:/code
    depends_on:
      - db
      - redis
    ports:
      - "7011:8000"
    networks:
      - app_net
  redis:
    container_name: redis
    image: redis:7
    restart: unless-stopped
    networks:
      - app_net
  celery:
    container_name: celery-worker
    build:
      context: ./Ecommerce_app
      dockerfile: Dockerfile.prod
    command: celery -A Ecommerce_app worker -l info
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      DJANGO_ENV: ${DJANGO_ENV}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      GRAPH_TENANT_ID: ${GRAPH_TENANT_ID}
      GRAPH_CLIENT_ID: ${GRAPH_CLIENT_ID}
      GRAPH_CLIENT_SECRET: ${GRAPH_CLIENT_SECRET}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      - django-backend-prod
      - redis
      - db
    networks:
      - app_net
  celery-beat:
    container_name: celery-beat
    build:
      context: ./Ecommerce_app
      dockerfile: Dockerfile.prod
    command: celery -A Ecommerce_app beat -l info
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      DJANGO_ENV: ${DJANGO_ENV}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      GRAPH_TENANT_ID: ${GRAPH_TENANT_ID}
      GRAPH_CLIENT_ID: ${GRAPH_CLIENT_ID}
      GRAPH_CLIENT_SECRET: ${GRAPH_CLIENT_SECRET}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
      - db
    networks:
      - app_net
  frontend-prod:
    container_name: frontend-prod
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile.prod
    ports:
      - "7010:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app_net

volumes:
  postgres_data:

networks:
  app_net:
