"""
Django settings for Ecommerce_app project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decimal import Decimal

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)  # Ensure /logs folder exists

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DJANGO_ENV = os.getenv("DJANGO_ENV", "development")

DEBUG = DJANGO_ENV != "PRODUCTION"

if not DEBUG:
    SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
    ALLOWED_HOSTS = [
        "arcadesticklabs.co.uk",
        "arcadesticklabs-test.ddns.net",
        "arcadesticklabs",
        "arcadesticklabs-test",
        "localhost",
        "127.0.0.1"
    ]
else:
    SECRET_KEY = 'django-insecure-zqh17d!1+t@2jvh7=jxry$s4^ivbyrh-$)4@%r!44%vgrw#zdq'
    ALLOWED_HOSTS = ["*"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

if os.environ.get("DJANGO_WATCH") == "1":
    # Forces Django to use polling instead of relying on inotify
    os.environ["DJANGO_AUTORELOAD_MODE"] = "stat"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Next.js dev server
    "http://127.0.0.1:3000",  # Sometimes needed for local dev
    "https://arcadesticklabs.co.uk",  # Production frontend
    "https://arcadesticklabs-test.ddns.net",  # UAT frontend
]

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID"),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET"),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    },
    "github": {
        "APP": {
            "client_id": os.environ.get("GITHUB_CLIENT_ID"),
            "secret": os.environ.get("GITHUB_CLIENT_SECRET"),
        },
        "SCOPE": ["user", "user:email"],
    },
}


# Allow cookies/authorization headers in cross-origin requests
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://arcadesticklabs.co.uk", # prod
    "https://arcadesticklabs-test.ddns.net" # UAT
]

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} [{name}:{lineno}] {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },

    "handlers": {
        # --- Console output ---
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },

        # --- File handler for PayPal logs ---
        "paypal_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "paypal.log",
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
        },

        # --- Optional file for general app logs ---
        "app_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": LOG_DIR / "app.log",
            "maxBytes": 10 * 1024 * 1024,  # 10 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
    },

    "root": {
        "handlers": ["console", "app_file"],
        "level": "INFO",
    },

    "loggers": {
        # PayPal Facade detailed logs
        "retail.facades.paypal_facade": {
            "handlers": ["console", "paypal_file"],
            "level": "DEBUG",  # capture all PayPal API details
            "propagate": False,
        },

        # Payment Service (Stripe, Orders, etc.)
        "retail.services.payment_service": {
            "handlers": ["console", "app_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

    # 3rd-party: REST & Auth
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.github",
    "dj_rest_auth",
    "dj_rest_auth.registration",
    "corsheaders",
    "import_export",
    "nested_admin",
    "django_json_widget",

    # Local apps
    "marketing",
    "retail.apps.RetailConfig",
    "users",
    "articles",
    "reviews"
]


from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=120),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "allauth.account.middleware.AccountMiddleware", 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_AUTH_SERIALIZERS = {
    "JWT_SERIALIZER": "users.serializers.CustomJWTSerializer",
}


if DEBUG:
    INSTALLED_APPS += ["debug_toolbar"]
    MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ( 
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

ROOT_URLCONF = 'Ecommerce_app.urls'

INTERNAL_IPS = ["127.0.0.1"]

# For Docker or complex networks
if DEBUG:
    import socket
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS += [ip[:-1] + "1" for ip in ips]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Ecommerce_app.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("POSTGRES_DB"),
        'USER': os.getenv("POSTGRES_USER"),
        'PASSWORD': os.getenv("POSTGRES_PASSWORD"),
        'HOST': os.getenv("POSTGRES_HOST"),  # this matches the docker-compose service name
        'PORT': '5432',
    }
}


# Authentication backends
# https://docs.djangoproject.com/en/5.1/topics/auth/customizing/#authentication-backends
AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",  # standard login
    "allauth.account.auth_backends.AuthenticationBackend",  # for social
)

# Redirects after login/logout
LOGIN_REDIRECT_URL = "http://localhost:3000/dashboard"
LOGOUT_REDIRECT_URL = "http://localhost:3000/login"

# Allow these frontend domains to receive redirects after OAuth login
ACCOUNT_ALLOWED_REDIRECT_DOMAINS = [
    "localhost:3000",
    "127.0.0.1:3000",
    "arcadesticklabs.co.uk",
]

# Required by django-allauth
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "static"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Stripe settings

STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")

# Slack webhook URL
SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL")

# Paypal settings
PAYPAL_CLIENT_ID = os.getenv("PAYPAL_CLIENT_ID")
PAYPAL_SECRET = os.getenv("PAYPAL_SECRET")
PAYPAL_API_BASE = os.getenv("PAYPAL_API_BASE")

# Required by django-allauth
SITE_ID = 1

# dj-rest-auth + allauth integration
REST_USE_JWT = True
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_SIGNUP_FIELDS = {
    "username": {"required": True},
    "email": {"required": True},
}

# Security settings for production
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SAMESITE = "None"

# Email settings
GRAPH_TENANT_ID = os.getenv("GRAPH_TENANT_ID")
GRAPH_CLIENT_ID = os.getenv("GRAPH_CLIENT_ID")
GRAPH_CLIENT_SECRET = os.getenv("GRAPH_CLIENT_SECRET")
GRAPH_SHARED_MAILBOX="no-reply@arcadesticklabs.co.uk"

# Frontend URL for email links
if DEBUG:
    FRONTENDURL = "http://localhost:3000"
else:
    FRONTENDURL = "https://arcadesticklabs.co.uk"

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# SendCloud settings
SENDCLOUD_SECRET_KEY = os.getenv("SENDCLOUD_SECRET_KEY")
SENDCLOUD_PUBLIC_KEY = os.getenv("SENDCLOUD_PUBLIC_KEY")

if DEBUG:
    SENDCLOUD_BASE_URL = "https://stoplight.io/mocks/sendcloud/sendcloud-public-api:v2/299107081"
else:
    SENDCLOUD_BASE_URL = "https://panel.sendcloud.sc/api/v2"

SENDCLOUD_FROM_POSTCODE = os.getenv("SENDCLOUD_FROM_POSTCODE")
SENDCLOUD_SENDER_ADDRESS_ID = os.getenv("SENDCLOUD_SENDER_ADDRESS_ID")
FREE_SHIPPING_THRESHOLD = Decimal("45.00")